In [30]:
import pandas as pd
import json
import pprint

In [36]:
baseball_df = pd.read_csv ('Cleaned_Data/all_data.csv')
del baseball_df["playerid"]
baseball_df

,AB,AVG,Age,H,HR,Name,OBP,OPS,Off,Position,R,RBI,SB,SLG,Season,Team,WAR
0,399,0.353,26,141,38,Frank Thomas,0.487,1.217,71.1,1B,106,101,2,0.729,1994,CHW,7.0
1,509,0.299,34,152,70,Mark McGwire,0.470,1.222,90.6,1B,130,147,1,0.752,1998,STL,8.5
2,423,0.312,32,132,52,Mark McGwire,0.467,1.198,68.4,1B,104,113,0,0.730,1996,OAK,7.3
3,400,0.368,26,147,39,Jeff Bagwell,0.451,1.201,66.3,1B,104,116,15,0.750,1994,HOU,7.8
4,580,0.372,26,216,42,Todd Helton,0.463,1.162,58.1,1B,138,147,5,0.698,2000,COL,8.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7891,388,0.209,23,81,0,Alfredo Griffin,0.243,0.531,-27.8,SS,30,21,8,0.289,1981,TOR,-1.7
7892,554,0.213,25,118,13,Andres Thomas,0.228,0.544,-35.8,SS,41,57,3,0.316,1989,ATL,-1.2
7893,587,0.211,24,124,0,Ozzie Smith,0.260,0.522,-37.4,SS,77,27,28,0.262,1979,SDP,0.7
7894,495,0.228,26,113,0,Hal Lanier,0.263,0.514,-34.9,SS,37,35,0,0.251,1969,SFG,0.7
7895,465,0.213,23,99,0,Tim Johnson,0.259,0.502,-34.3,SS,39,32,6,0.243,1973,MIL,-1.7

In [37]:
baseball_df.to_json('Front_End/all_data.json')
baseball_df.to_html('Front_End/all_data.html')